### ISSUE TITLE
1.20.1 Issue

### ISSUE THREAD

**Issue by mehboss** [BananaPuncher714/NBTEditor#40]
There seems to be an issue observed on 1.20 servers with a method exception and I was wondering if you could provide any insight. Perhaps it is something I am doing wrong

```
	ItemStack applyNBT(ItemStack item, Object value, String... path) {

		if (path == null || path.length == 0) {
			throw new IllegalArgumentException("NBT path cannot be null or empty");
		}
		return NBTEditor.set(item, value, (Object[]) path);
	}

```

![Image](https://github.com/user-attachments/assets/cb466236-f2e2-4d71-9d25-3c595c486a29)

**Comment by BananaPuncher714** [comment]
What  is the exact server version? Can you try removing the NBTEditor from your local maven cache and re-download it again? There was an issue before which I resolved in c5aedb96400daa5889bf3e055f26ae71ba286821 which may be the issue you are seeing.

**Comment by mehboss** [comment]
The exact server version is 

`[17:59:07] [Server thread/INFO]: This server is running CraftBukkit version 3871-Spigot-d2eba2c-3f9263b (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
[17:59:07] [Server thread/INFO]: Checking version, please wait...
[17:59:07] [Thread-9/INFO]: You are 52 version(s) behind
`

Pom
`		<dependency>
			<groupId>io.github.bananapuncher714</groupId>
			<artifactId>nbteditor</artifactId>
			<version>7.19.7</version>
		</dependency>`

**Comment by mehboss** [comment]
> What is the exact server version? Can you try removing the NBTEditor from your local maven cache and re-download it again? There was an issue before which I resolved in [c5aedb9](https://github.com/BananaPuncher714/NBTEditor/commit/c5aedb96400daa5889bf3e055f26ae71ba286821) which may be the issue you are seeing.

Hello again,
I have tried to remove my local maven cache and have the file redownload for the dependency, but I am still getting the same error.
`[22:07:00] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.a(net.minecraft.core.HolderLookup$a)
[22:07:00] [Server thread/WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2395)
[22:07:00] [Server thread/WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor$ReflectionTarget.fetchMethod(NBTEditor.java:1861)
[22:07:00] [Server thread/WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.getMethod(NBTEditor.java:232)
[22:07:00] [Server thread/WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.setItemTag(NBTEditor.java:557)
[22:07:00] [Server thread/WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.set(NBTEditor.java:1275)
[22:07:00] [Server thread/WARN]:        at me.mehboss.recipe.RecipeManager.handleIdentifier(RecipeManager.java:303)
[22:07:00] [Server thread/WARN]:        at me.mehboss.recipe.RecipeManager.addRecipes(RecipeManager.java:732)
[22:07:00] [Server thread/WARN]:        at me.mehboss.recipe.Main.onEnable(Main.java:292)
[22:07:00] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[22:07:00] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[22:07:00] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[22:07:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:546)
[22:07:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:460)
[22:07:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:588)
[22:07:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:413)
[22:07:00] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[22:07:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972)
[22:07:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[22:07:00] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[22:07:00] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.a(net.minecraft.core.HolderLookup$a,net.minecraft.nbt.NBTTagCompound)
[22:07:00] [Server thread/WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2395)
[22:07:00] [Server thread/WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor$ReflectionTarget.fetchMethod(NBTEditor.java:1861)
[22:07:00] [Server thread/WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.getMethod(NBTEditor.java:232)
[22:07:00] [Server thread/WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.createItemStack(NBTEditor.java:311)
[22:07:00] [Server thread/WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.setItemTag(NBTEditor.java:583)
[22:07:00] [Server thread/WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.set(NBTEditor.java:1275)
[22:07:00] [Server thread/WARN]:        at me.mehboss.recipe.RecipeManager.handleIdentifier(RecipeManager.java:303)
[22:07:00] [Server thread/WARN]:        at me.mehboss.recipe.RecipeManager.addRecipes(RecipeManager.java:732)
[22:07:00] [Server thread/WARN]:        at me.mehboss.recipe.Main.onEnable(Main.java:292)
[22:07:00] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[22:07:00] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[22:07:00] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[22:07:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:546)
[22:07:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:460)
[22:07:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:588)
[22:07:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:413)
[22:07:00] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[22:07:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972)
[22:07:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[22:07:00] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[22:07:00] [Server thread/ERROR]: Error occurred while enabling CustomRecipes v1.9.8.7 (Is it up to date?)`

![Image](https://github.com/user-attachments/assets/428bfeb0-9bd9-4a6a-b370-50b8cafa7aaf)

**Comment by mehboss** [comment]
Actually, I lied. It looks like it didn't pull correctly again. Any idea why?

![Image](https://github.com/user-attachments/assets/f00a5638-8837-4eec-b96f-4cc8b17e42d3)

**Comment by mehboss** [comment]
Got it! Had to dig in and delete the cache completely.
Thank you for your help, all set.
